server:
  port: 9999

spring:
  application:
    name: CLOUD-HYSTRIX
  cloud:
    consul:
      host: localhost
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: "*"