server:
  port: 8081

spring:
  application:
    name: CONSUL-CLIENT
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: true
        service-name: ${spring.application.name}